name: Purge CDN Cache

on:
  schedule:
    - cron: '*/15 * * * *'  # Run every 15 mins
  workflow_dispatch:  # Allow manual triggers
  workflow_run:
    workflows: ["blank.yml"]  # Name of the workflow to depend on
    types:
      - completed  # Trigger when the referenced workflow completes successfully

jobs:
  purge-cdn-json-files-daa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository - alihusains/daa
        uses: actions/checkout@v3
        with:
          repository: alihusains/daa
          ref: ${{ github.ref }}

      - name: Find JSON files and Purge CDN Cache - alihusains/daa
        id: purge_json_daa
        run: |
          baseUrl="https://cdn.jsdelivr.net/gh/alihusains/daa@latest/"
          urls=""
          find . -name "*.json" -type f | while read file; do
            filePath="${file#./}"
            urls+="${baseUrl}${filePath},"
          done
          echo "urls=${urls%,*}" >> $GITHUB_ENV

      - name: Purge CDN Caches - alihusains/daa
        uses: egad13/purge-jsdelivr-cache@v1
        with:
          url: ${{ steps.purge_json_daa.outputs.urls }}
