name: Purge CDN Cache - daa

on:
  schedule:
    - cron: '*/15 * * * *'  # Run every 15 mins
  workflow_dispatch:  # Allow manual triggers
  workflow_run:
    workflows: ["blank.yml"]  # Name of the workflow to depend on
    types:
      - completed  # Trigger when the referenced workflow completes successfully

jobs:
  purge-cdn-json-files-daa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository - alihusains/daa
        uses: actions/checkout@v3
        with:
          repository: alihusains/daa
          ref: ${{ github.ref }}

      - name: Find and Log JSON files - alihusains/daa
        id: find_and_log_json_daa
        run: |
          json_files=$(find . -name "*.json" -type f)
          if [ -n "$json_files" ]; then
            echo "::set-output name=found_json_files::${json_files}"
            echo "Found JSON files:"
            echo "${json_files}"
          else
            echo "No JSON files found."
            exit 1
          fi

      - name: Purge CDN Caches - alihusains/daa
        if: success() && steps.find_and_log_json_daa.outputs.found_json_files
        run: |
          urls=""
          for file in ${{ steps.find_and_log_json_daa.outputs.found_json_files }}; do
            urls+="https://cdn.jsdelivr.net/gh/alihusains/daa@latest/${file},"
          done
          urls="${urls%,}"
          echo "urls=${urls}" >> $GITHUB_ENV

          echo "Purging CDN caches..."
          echo "urls=${urls}"

          # Use the purge-jsdelivr-cache action with the collected URLs
          uses: egad13/purge-jsdelivr-cache@v1
          with:
            url: ${{ env.urls }}
