name: Purge CDN Cache - daa

on:
  schedule:
    - cron: '*/15 * * * *'  # Run every 15 mins
  workflow_dispatch:  # Allow manual triggers
  workflow_run:
    workflows: ["blank.yml"]  # Name of the workflow to depend on
    types:
      - completed  # Trigger when the referenced workflow completes successfully

jobs:
  purge-cdn-json-files-daa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository - alihusains/daa
        uses: actions/checkout@v3
        with:
          repository: alihusains/daa
          ref: ${{ github.ref }}

      - name: Find and Log JSON files - alihusains/daa
        id: find_and_log_json_daa
        run: |
          json_files=$(find . -name "*.json" -type f)
          if [ -n "$json_files" ]; then
            echo "Found JSON files:"
            echo "${json_files}" > json_files.txt  # Save JSON files to a file
          else
            echo "No JSON files found."
            exit 1
          fi

      - name: Determine CDN URLs to Purge
        id: purge_urls
        run: |
          baseUrl="https://cdn.jsdelivr.net/gh/alihusains/daa@latest"
          urls=""
          while IFS= read -r file; do
            file=${file#./}  # Remove leading './' from file path if present
            urls+="${baseUrl}/${file},"
          done < json_files.txt  # Read JSON files from the file
          urls="${urls%,}"  # Remove trailing comma
          echo "::set-output name=urls::${urls}"

      - name: Purge CDN Caches
        uses: egad13/purge-jsdelivr-cache@v1
        with:
          url: ${{ steps.purge_urls.outputs.urls }}
