name: Purge CDN Cache

on:
  schedule:
    - cron: '*/15 * * * *'  # Run every 15 mins
  workflow_dispatch:  # Allow manual triggers
  workflow_run:
    workflows: ["blank.yml"]  # Name of the workflow to depend on
    types:
      - completed  # Trigger when the referenced workflow completes successfully

jobs:
  purge-jsdelivr-cache:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Determine CDN URLs to Purge
        id: purge_urls
        run: |
          baseUrl="https://cdn.jsdelivr.net/gh/${{ github.repository }}@latest"
          urls=""
          for f in $(find dist -name "*.json" -type f); do
            # Strip the 'dist/' prefix from the file path
            filePath="${f#dist/}"
            urls+="${baseUrl}/${filePath},"
          done
          if [ -n "$urls" ]; then
            echo "urls=${urls%,*}" >> $GITHUB_ENV
          else
            echo "No URLs to purge."
            exit 1
          fi

      - name: Purge CDN Caches
        uses: egad13/purge-jsdelivr-cache@v1
        with:
          url: ${{ env.urls }}
