name: Purge CDN Cache

on:
  schedule:
    - cron: '*/15 * * * *'  # Run every 15 mins
  workflow_dispatch:  # Allow manual triggers
  workflow_run:
    workflows: ["blank.yml"]  # Name of the workflow to depend on
    types:
      - completed  # Trigger when the referenced workflow completes successfully

jobs:
  purge-jsdelivr-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Determine CDN URLs to Purge
        id: purge_urls
        run: |
          baseUrl="https://cdn.jsdelivr.net/gh/"
          urls=""
          repos=(
            "alihusains/daa"
            "alihusains/dnaa"
            "alihusains/stdb"
            # Add more repositories as needed
          )
          for repo in "${repos[@]}"; do
            # Check if 'database' folder exists in the repository
            if [ -d "${repo}/database" ]; then
              # Find .db files in the 'database' folder
              for f in $(find "${repo}/database" -name "*.db" -type f); do
                # Strip the '<repo>/' prefix from the file path
                filePath="${f#${repo}/}"
                urls+="${baseUrl}${repo}@latest/${filePath},"
              done
            fi
            # Find .json files in the root of the repository
            for f in $(find "${repo}" -maxdepth 1 -name "*.json" -type f); do
              # Strip the '<repo>/' prefix from the file path
              filePath="${f#${repo}/}"
              urls+="${baseUrl}${repo}@latest/${filePath},"
            done
          done
          if [ -n "$urls" ]; then
            echo "urls=${urls%,*}" >> $GITHUB_ENV
          else
            echo "No URLs to purge."
            exit 1
          fi

      - name: Purge CDN Caches
        uses: egad13/purge-jsdelivr-cache@v1
        with:
          url: ${{ env.urls }}
