name: Purge CDN Cache

on:
  schedule:
    - cron: '*/15 * * * *'  # Run every 15 mins
  workflow_dispatch:  # Allow manual triggers
  workflow_run:
    workflows: ["blank.yml"]  # Name of the workflow to depend on
    types:
      - completed  # Trigger when the referenced workflow completes successfully

jobs:
  purge-cdn-json-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository - alihusains/daa
        uses: actions/checkout@v3
        with:
          repository: alihusains/daa
          ref: ${{ github.ref }}

      - name: Find JSON files and Purge CDN Cache
        id: purge_json
        run: |
          baseUrl="https://cdn.jsdelivr.net/gh/alihusains/daa@latest/"
          find . -name "*.json" -type f | while read file; do
            filePath="${file#./}"
            echo "Purging ${baseUrl}${filePath}"
            curl -X PURGE "${baseUrl}${filePath}"
          done
